[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Josh Hsieh", email = "jtr860830@gmail.com"},
]
dependencies = [
    "pygame>=2.1.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
